SELECT SUM(Altura) AS SOMA_ALTURAS FROM Aluno
SELECT SUM(Altura) AS SOMA_ALTURAS_REPROVADOS FROM Aluno WHERE Aprovado = 'False'
SELECT COUNT(*) AS QNT_REGISTROS FROM Aluno
SELECT MAX(Altura) AS MAIOR_ALTURA FROM Aluno
SELECT MIN(Altura) AS MENOR_ALTURA FROM Aluno
SELECT COUNT(*) AS APROVADOS FROM Aluno  where Aprovado = 'True'